/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as FacilitiesIndexImport } from './routes/facilities/index'
import { Route as FacilitiesFacilityIdImport } from './routes/facilities/$facilityId'
import { Route as FacilitiesFacilityIdTimeSlotsIndexImport } from './routes/facilities_.$facilityId/timeSlots/index'
import { Route as FacilitiesFacilityIdTimeSlotsTimeSlotIdImport } from './routes/facilities_.$facilityId/timeSlots/$timeSlotId'
import { Route as FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexImport } from './routes/facilities_.$facilityId/timeSlots_.$timeSlotId/reservations/index'
import { Route as FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdImport } from './routes/facilities_.$facilityId/timeSlots_.$timeSlotId/reservations/$reservationId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const FacilitiesIndexRoute = FacilitiesIndexImport.update({
  id: '/facilities/',
  path: '/facilities/',
  getParentRoute: () => rootRoute,
} as any)

const FacilitiesFacilityIdRoute = FacilitiesFacilityIdImport.update({
  id: '/facilities/$facilityId',
  path: '/facilities/$facilityId',
  getParentRoute: () => rootRoute,
} as any)

const FacilitiesFacilityIdTimeSlotsIndexRoute =
  FacilitiesFacilityIdTimeSlotsIndexImport.update({
    id: '/facilities_/$facilityId/timeSlots/',
    path: '/facilities/$facilityId/timeSlots/',
    getParentRoute: () => rootRoute,
  } as any)

const FacilitiesFacilityIdTimeSlotsTimeSlotIdRoute =
  FacilitiesFacilityIdTimeSlotsTimeSlotIdImport.update({
    id: '/facilities_/$facilityId/timeSlots/$timeSlotId',
    path: '/facilities/$facilityId/timeSlots/$timeSlotId',
    getParentRoute: () => rootRoute,
  } as any)

const FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexRoute =
  FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexImport.update({
    id: '/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/',
    path: '/facilities/$facilityId/timeSlots/$timeSlotId/reservations/',
    getParentRoute: () => rootRoute,
  } as any)

const FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdRoute =
  FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdImport.update(
    {
      id: '/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/$reservationId',
      path: '/facilities/$facilityId/timeSlots/$timeSlotId/reservations/$reservationId',
      getParentRoute: () => rootRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/facilities/$facilityId': {
      id: '/facilities/$facilityId'
      path: '/facilities/$facilityId'
      fullPath: '/facilities/$facilityId'
      preLoaderRoute: typeof FacilitiesFacilityIdImport
      parentRoute: typeof rootRoute
    }
    '/facilities/': {
      id: '/facilities/'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/facilities_/$facilityId/timeSlots/$timeSlotId': {
      id: '/facilities_/$facilityId/timeSlots/$timeSlotId'
      path: '/facilities/$facilityId/timeSlots/$timeSlotId'
      fullPath: '/facilities/$facilityId/timeSlots/$timeSlotId'
      preLoaderRoute: typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdImport
      parentRoute: typeof rootRoute
    }
    '/facilities_/$facilityId/timeSlots/': {
      id: '/facilities_/$facilityId/timeSlots/'
      path: '/facilities/$facilityId/timeSlots'
      fullPath: '/facilities/$facilityId/timeSlots'
      preLoaderRoute: typeof FacilitiesFacilityIdTimeSlotsIndexImport
      parentRoute: typeof rootRoute
    }
    '/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/$reservationId': {
      id: '/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/$reservationId'
      path: '/facilities/$facilityId/timeSlots/$timeSlotId/reservations/$reservationId'
      fullPath: '/facilities/$facilityId/timeSlots/$timeSlotId/reservations/$reservationId'
      preLoaderRoute: typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdImport
      parentRoute: typeof rootRoute
    }
    '/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/': {
      id: '/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/'
      path: '/facilities/$facilityId/timeSlots/$timeSlotId/reservations'
      fullPath: '/facilities/$facilityId/timeSlots/$timeSlotId/reservations'
      preLoaderRoute: typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/facilities': typeof FacilitiesIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/facilities/$facilityId/timeSlots/$timeSlotId': typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdRoute
  '/facilities/$facilityId/timeSlots': typeof FacilitiesFacilityIdTimeSlotsIndexRoute
  '/facilities/$facilityId/timeSlots/$timeSlotId/reservations/$reservationId': typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdRoute
  '/facilities/$facilityId/timeSlots/$timeSlotId/reservations': typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/facilities': typeof FacilitiesIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/facilities/$facilityId/timeSlots/$timeSlotId': typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdRoute
  '/facilities/$facilityId/timeSlots': typeof FacilitiesFacilityIdTimeSlotsIndexRoute
  '/facilities/$facilityId/timeSlots/$timeSlotId/reservations/$reservationId': typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdRoute
  '/facilities/$facilityId/timeSlots/$timeSlotId/reservations': typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/facilities/': typeof FacilitiesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/facilities_/$facilityId/timeSlots/$timeSlotId': typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdRoute
  '/facilities_/$facilityId/timeSlots/': typeof FacilitiesFacilityIdTimeSlotsIndexRoute
  '/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/$reservationId': typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdRoute
  '/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/': typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/facilities/$facilityId'
    | '/facilities'
    | '/login'
    | '/register'
    | '/facilities/$facilityId/timeSlots/$timeSlotId'
    | '/facilities/$facilityId/timeSlots'
    | '/facilities/$facilityId/timeSlots/$timeSlotId/reservations/$reservationId'
    | '/facilities/$facilityId/timeSlots/$timeSlotId/reservations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/facilities/$facilityId'
    | '/facilities'
    | '/login'
    | '/register'
    | '/facilities/$facilityId/timeSlots/$timeSlotId'
    | '/facilities/$facilityId/timeSlots'
    | '/facilities/$facilityId/timeSlots/$timeSlotId/reservations/$reservationId'
    | '/facilities/$facilityId/timeSlots/$timeSlotId/reservations'
  id:
    | '__root__'
    | '/'
    | '/facilities/$facilityId'
    | '/facilities/'
    | '/login/'
    | '/register/'
    | '/facilities_/$facilityId/timeSlots/$timeSlotId'
    | '/facilities_/$facilityId/timeSlots/'
    | '/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/$reservationId'
    | '/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacilitiesFacilityIdRoute: typeof FacilitiesFacilityIdRoute
  FacilitiesIndexRoute: typeof FacilitiesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  FacilitiesFacilityIdTimeSlotsTimeSlotIdRoute: typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdRoute
  FacilitiesFacilityIdTimeSlotsIndexRoute: typeof FacilitiesFacilityIdTimeSlotsIndexRoute
  FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdRoute: typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdRoute
  FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexRoute: typeof FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacilitiesFacilityIdRoute: FacilitiesFacilityIdRoute,
  FacilitiesIndexRoute: FacilitiesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  FacilitiesFacilityIdTimeSlotsTimeSlotIdRoute:
    FacilitiesFacilityIdTimeSlotsTimeSlotIdRoute,
  FacilitiesFacilityIdTimeSlotsIndexRoute:
    FacilitiesFacilityIdTimeSlotsIndexRoute,
  FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdRoute:
    FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsReservationIdRoute,
  FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexRoute:
    FacilitiesFacilityIdTimeSlotsTimeSlotIdReservationsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/facilities/$facilityId",
        "/facilities/",
        "/login/",
        "/register/",
        "/facilities_/$facilityId/timeSlots/$timeSlotId",
        "/facilities_/$facilityId/timeSlots/",
        "/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/$reservationId",
        "/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/facilities/$facilityId": {
      "filePath": "facilities/$facilityId.tsx"
    },
    "/facilities/": {
      "filePath": "facilities/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/facilities_/$facilityId/timeSlots/$timeSlotId": {
      "filePath": "facilities_.$facilityId/timeSlots/$timeSlotId.tsx"
    },
    "/facilities_/$facilityId/timeSlots/": {
      "filePath": "facilities_.$facilityId/timeSlots/index.tsx"
    },
    "/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/$reservationId": {
      "filePath": "facilities_.$facilityId/timeSlots_.$timeSlotId/reservations/$reservationId.tsx"
    },
    "/facilities_/$facilityId/timeSlots_/$timeSlotId/reservations/": {
      "filePath": "facilities_.$facilityId/timeSlots_.$timeSlotId/reservations/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
