/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as FacilitiesIndexImport } from './routes/facilities/index'
import { Route as FacilitiesFacilityIdImport } from './routes/facilities/$facilityId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const FacilitiesIndexRoute = FacilitiesIndexImport.update({
  id: '/facilities/',
  path: '/facilities/',
  getParentRoute: () => rootRoute,
} as any)

const FacilitiesFacilityIdRoute = FacilitiesFacilityIdImport.update({
  id: '/facilities/$facilityId',
  path: '/facilities/$facilityId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/facilities/$facilityId': {
      id: '/facilities/$facilityId'
      path: '/facilities/$facilityId'
      fullPath: '/facilities/$facilityId'
      preLoaderRoute: typeof FacilitiesFacilityIdImport
      parentRoute: typeof rootRoute
    }
    '/facilities/': {
      id: '/facilities/'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/facilities': typeof FacilitiesIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/facilities': typeof FacilitiesIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/facilities/': typeof FacilitiesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/facilities/$facilityId'
    | '/facilities'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/facilities/$facilityId' | '/facilities' | '/login' | '/register'
  id:
    | '__root__'
    | '/'
    | '/facilities/$facilityId'
    | '/facilities/'
    | '/login/'
    | '/register/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacilitiesFacilityIdRoute: typeof FacilitiesFacilityIdRoute
  FacilitiesIndexRoute: typeof FacilitiesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacilitiesFacilityIdRoute: FacilitiesFacilityIdRoute,
  FacilitiesIndexRoute: FacilitiesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/facilities/$facilityId",
        "/facilities/",
        "/login/",
        "/register/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/facilities/$facilityId": {
      "filePath": "facilities/$facilityId.tsx"
    },
    "/facilities/": {
      "filePath": "facilities/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
